[workspace]
resolver = "2"
members = ["programs/*"]

[workspace.dependencies]
mollusk-svm = "0.4.1"
mollusk-svm-bencher = "0.4.1"
pinocchio = "0.9.0"
pinocchio-pubkey = "0.3.0"
pinocchio-system = "0.3.0"
solana-client = "2.3.6"
solana-program-runtime = "2.3.6"
solana-sdk = "2.3.1"